### ISSUE TITLE
System.NullReferenceException error

### ISSUE THREAD

**Issue by dapal-003** [Ezzpify/HourBoostr#123]
While running the latest version (3.1.0) of singleBoostr I get the following error message.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SingleBoostr.MainForm.ConnectToSteam()
   at SingleBoostr.MainForm.<InitializeApp>d__127.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```
While I start the application up steam is already running and logged in.

**Comment by Ezzpify** [comment]
Hey. Going to look for a fix. For now disable steam beta participation and it will work.

**Comment by Ezzpify** [comment]
Issue has been fixed.
