### ISSUE TITLE
how to fix ?

### ISSUE THREAD

**Issue by reawz7192** [Ezzpify/HourBoostr#44]
Warn: Exception occured for callbackManager: System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at HourBoostr.Bot.Connect()
   at HourBoostr.Bot.OnDisconnected(DisconnectedCallback callback)
   at SteamKit2.Callback`1.Run(Object callback)
   at SteamKit2.CallbackManager.<>c__DisplayClass11_0.<Handle>b__1(CallbackBase callback)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at SteamKit2.CallbackManager.Handle(ICallbackMsg call)
   at HourBoostr.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs)
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

**Comment by nicopxxch** [comment]
Use the linux hour boost, this program is pretty much dead and if you get it running it still isn't as good as the others.
